### DISCUSSION TITLE
Font size

### DISCUSSION THREAD

**Discussion by doublejz** [MMRIZE/MMM-CalendarExt3Agenda#29] [General]
Are there any configuration options in change font or increase overall size. I know in the other modules we have a fontSize or eventHeight.

Just curious as I have a smaller screen and would like to "stretch" the overall display of MMM-CalendarExt3Agenda to be larger. IE. middle would literally fill the middle from left -> right.

**Comment by eouia** [comment]
There is no configuration for Looking. All modification of looks be performed by CSS. 
You can add this into your `css/custom.css`.
```css
.CX3A {
  font-size: 20px; /* <-- Originally it was 16px; */
}
```
Or you can adjust any selection.

```css
.CX3A .event .title {
  font-size: 22px; /* <-- Or something whatever */
}
```

For the second question, you can use other position like `bottom_bar`...
And adjust width of module

```css
.CX3A.bodice {
  width: 800px;
}
```
However sometimes module's width might be determined not only by itself but also by other module's interference.

**Reply by devonian79** [reply]
I tried digging around to see if its easy for me to figure out but I can't seem to do it.

I found where I can change the the color for "today" to "gold," for example, but I can't change the event entries for "today" to a different size, weight, or color... that I can find. Is it possible to do that?

Thank you!

**Reply by eouia** [reply]
![image](https://github.com/MMRIZE/MMM-CalendarExt3Agenda/assets/1720610/9b02feb0-f9e0-4210-8fcd-0991e778d2b4)

```css
.CX3A .cell.today {
  background-color: rgb(255 255 0/50%);
  font-size: 150%;
}

.CX3A .cell.today .title {
  color: magenta;
}
```
