### DISCUSSION TITLE
Show symbols also in full-day events

### DISCUSSION THREAD

**Discussion by Zaro-kar** [MMRIZE/MMM-CalendarExt3Agenda#72] [Q&A] [answered]
Is there a way to display the calendar symbol for all-day events?

In addition to the color differentiation of the calendars, this would be very helpful and neat.
For example, I have a calendar for holidays and a calendar for birthdays. If there was an icon for each event name, it would look much better.

**Comment by eouia** [comment, marked as answer]
```css
/* css/custom.css */
.CX3A .cellBody .fullday .event .headline .symbol,
.CX3A .cellBody .fullday .event .headline .symbol * {
  display: block;
  color: var(--oppositeColor);
}
```


<img width="344" alt="image" src="https://github.com/user-attachments/assets/9cad4aae-d29d-4a38-8e07-2457ca014fcc" />
