### ISSUE TITLE
module position other than left or right cause weird font sizes

### ISSUE THREAD

**Issue by sdetweil** [MMRIZE/MMM-CalendarExt3Agenda#14]
.CX3A  has max-width:400px..   

user wants to put in center , as only thing on 'page' with pages. 
or fullscreen_above/below (as only thing on page)

you can do this
```css
.CX3A.bodice {
      max-width: 100% ;
      font-size: 30px;
}
```
.CX3A doesn't override
```css
.CX3A {
      max-width: 100% ;
      font-size: 30px;
}
```
but jams left edge to screen edge in fullscreen(either) 
causes weird right clip on top/bottom_center
