### ISSUE TITLE
instanceId seems to do nothing

### ISSUE THREAD

**Issue by BKeyport** [MMRIZE/MMM-CalendarExt3Agenda#18]
I have ~~three~~ two instances of CX3A running (Intended to be three). 

To keep them separate, I'm using instance ID's of 1, 2 ~~,and 3~~ in the configs. I can't find anywhere they are instance id is shown in the resulting HTML/CSS code. 

```js
config: {
	instanceId: 2,
```

The eventual want/need: I want to be able to run multiple instances in the same MM area, next to each other, like I have my top bar configured. 

``` css
/* adjust top bar modules to display side by side */
.MMM-FlipClock, .MMM-Worldclock, .MMM-Multimonth, .MMM-ValuesByNotification {
	display: inline-flex;
}

/* adjust CX3A modules to display side by side  "idea"*/
/* .CX3A_2 CX3A_3 {
	display: inline-flex;
}*/
```
Thanks!

**Comment by eouia** [comment]
![image](https://user-images.githubusercontent.com/1720610/219980710-6eb93ca2-78c6-47db-8fee-76ad0cb073a7.png)

![image](https://user-images.githubusercontent.com/1720610/219980740-edcd929f-8e08-4b7d-afef-f10ded9afe4f.png)

![image](https://user-images.githubusercontent.com/1720610/219980663-afc5096f-1d5b-4a2c-8cb6-e71562f84cc3.png)

**Comment by eouia** [comment]
Is this what you want?
![image](https://user-images.githubusercontent.com/1720610/219980981-82b02463-de61-43e2-93ce-7e96b358d8e4.png)

**Comment by BKeyport** [comment]
Exactly what I want on the 2nd post, yes. 

As for the instance ID - I'm not getting any adjustments based on the instance. 

```css
.CX3A_1 {
   border: 2px solid red; 
 }
 
.CX3A_2 { 
	border: 2px solid blue;
}

.CX3A_3 {
	border: 2px solid green;
}
```

```
		{
			module: "MMM-CalendarExt3Agenda", // https://github.com/MMRIZE/MMM-CalendarExt3Agenda
			position: "top_center",
			config: {
				instanceId: "2",
				showMiniMonthCalendar: false,
				instanceId: "basicCalendar",
				firstDayOfWeek: 0,
				startDayIndex: 0,
				endDayIndex: 7,
				minimalDaysOfNewYear: 1,
				animationSpeed: 0,
				useSymbol: false,
				useWeather: false,
				calendarSet: ["Seahawks", "Sounders", "Bluejays", "Mariners", "Kraken", "Huskies", "XFL"],
				//calendarSet: ["Seahawks", "Sounders", "Bluejays", "Mariners", "Kraken", "Huskies", "XFL", "IRS",], // used until I can stack sideways. 
				eventTransformer: (ev) => {
					if (ev.title.search("⚾") > -1) {
						ev.title = ev.title.replace("⚾️ ","");
					}
					if (ev.title.search("Bowling") > -1) {
						ev.color = 'yellow';
					}
					if (ev.title.search("🏈") > -1) { 
						ev.title = ev.title.replace("🏈 ","");
					}
					return ev
				},
			},
		},
		{
			module: "MMM-CalendarExt3Agenda", // https://github.com/MMRIZE/MMM-CalendarExt3Agenda
			position: "top_center",
			config: {
				instanceId: "3",
				showMiniMonthCalendar: false,
				instanceId: "basicCalendar",
				firstDayOfWeek: 0,
				startDayIndex: 0,
				endDayIndex: 99,
				minimalDaysOfNewYear: 1,
				animationSpeed: 0,
				useSymbol: false,
				useWeather: false,
				calendarSet: ["IRS"],
				eventTransformer: (ev) => {
					if (ev.title.search("⚾") > -1) {
						ev.title = ev.title.replace("⚾️ ","");
					}
					if (ev.title.search("Bowling") > -1) {
						ev.color = 'yellow';
					}
					if (ev.title.search("🏈") > -1) { 
						ev.title = ev.title.replace("🏈 ","");
					}
					return ev
				},
			},
		},
```
![image](https://user-images.githubusercontent.com/44744076/219983198-248ba32a-27aa-4a8e-a2ec-ceb84bfae562.png)
